name: Deploy to FTP
on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
    - main
    - production
  workflow_dispatch:
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-lastest
    steps:
    - name: Get the code
      uses: actions/checkout@v3

    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        serwer: 20.16.109.51
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: www/
        
